---
sudo: required
services: docker
language: python

env:
  global:
    - ROLE_NAME: k8s-dashboard

install:
  # Install test dependencies.
  - pip install molecule docker

script:
  # Run tests.
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/?branch=master
