---
sudo: required
services: docker
language: minimal

env:
  global:
    - ROLE_NAME: k8s-dashboard

install:
  # Install test dependencies.
  - pip install molecule docker

before_script:
  # Use actual Ansible Galaxy role name for the project directory.
  - cd ../
  - mv ansible-role-$ROLE_NAME moikot.$ROLE_NAME
  - cd moikot.$ROLE_NAME

script:
  # Run tests.
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
