---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: molecule/default/yaml-lint.yml
platforms:
  - name: instance
    groups:
      - k8s
    image: bsycorp/kind:latest-1.14
    privileged: true
    override_command: false
    exposed_ports:
      - 8443/tcp
      - 10080/tcp
    published_ports:
      - 0.0.0.0:${TEST_CLUSTER_PORT:-10443}:8443/tcp
    pre_build_image: true
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-playbook.yml}
  env:
    K8S_AUTH_KUBECONFIG: /tmp/molecule/kubeconfig
    KUBECONFIG: /tmp/molecule/kubeconfig
    KIND_PORT: '${TEST_CLUSTER_PORT:-10443}'
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
