---
- name: Converge
  hosts: all

  vars:
    k8s_dashboard_cluster_role: cluster-admin

    k8s_dashboard_args:
      - --enable-skip-login
      - --disable-settings-authorizer
      - --auto-generate-certificates
      - --namespace=kubernetes-dashboard

    metrics_scraper_image: moikot/dashboard-metrics-sidecar  

  roles:
    - role: moikot.k8s_dashboard
